export enum CommandType {
  DRAW_PLOT = "DRAW_PLOT",
  DRAW_ROOM = "DRAW_ROOM",
  DRAW_DOOR = "DRAW_DOOR",
  DRAW_WINDOW = "DRAW_WINDOW",
  DRAW_TEXT = "DRAW_TEXT",
  DRAW_DIMENSION = "DRAW_DIMENSION",
}
