/**
 * Command Generator Service — wraps the core command generator and adds
 * AI-specific logic like auto-generating doors/windows when missing.
 */

import type { Blueprint } from "@/blueprint/types/blueprint";
import type { BlueprintCommand } from "@/blueprint/commands/command";
import { generateCommands as coreGenerateCommands } from "@/blueprint/generators/command-generator";

export function generateCommandsFromBlueprint(blueprint: Blueprint): BlueprintCommand[] {
  const enriched = enrichBlueprint(blueprint);
  return coreGenerateCommands(enriched);
}

function enrichBlueprint(bp: Blueprint): Blueprint {
  let doors = [...bp.doors];
  let windows = [...bp.windows];

  if (doors.length === 0) {
    doors = autoGenerateDoors(bp);
  }

  if (windows.length === 0) {
    windows = autoGenerateWindows(bp);
  }

  return { ...bp, doors, windows };
}

function autoGenerateDoors(bp: Blueprint): { id: string; x: number; y: number; width: number }[] {
  const doors: { id: string; x: number; y: number; width: number }[] = [];
  let id = 1;

  for (const room of bp.rooms) {
    if (room.type === "garden" || room.type === "hallway") continue;

    doors.push({
      id: `d${id++}`,
      x: room.x + room.width / 2,
      y: room.y + room.height,
      width: 3,
    });
  }

  return doors;
}

function autoGenerateWindows(bp: Blueprint): { id: string; x: number; y: number; width: number }[] {
  const windows: { id: string; x: number; y: number; width: number }[] = [];
  let id = 1;
  const pw = bp.plot.width;
  const ph = bp.plot.height;

  for (const room of bp.rooms) {
    if (room.type === "hallway" || room.type === "garage") continue;

    if (room.y <= 0 && room.width >= 6) {
      windows.push({
        id: `w${id++}`,
        x: room.x + room.width / 2,
        y: room.y,
        width: Math.min(4, room.width * 0.35),
      });
    }
    if (room.y + room.height >= ph - 1 && room.width >= 6) {
      windows.push({
        id: `w${id++}`,
        x: room.x + room.width / 2,
        y: room.y + room.height,
        width: Math.min(4, room.width * 0.35),
      });
    }
    if (room.x <= 0 && room.height >= 6) {
      windows.push({
        id: `w${id++}`,
        x: room.x,
        y: room.y + room.height / 2,
        width: Math.min(4, room.height * 0.35),
      });
    }
    if (room.x + room.width >= pw - 1 && room.height >= 6) {
      windows.push({
        id: `w${id++}`,
        x: room.x + room.width,
        y: room.y + room.height / 2,
        width: Math.min(4, room.height * 0.35),
      });
    }
  }

  return windows;
}
